### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by rlepinski**

### CODE REVIEW

**Comment by madelgi** [comment]
🌵

**Comment by BrianBatchelder** [comment]
I hadn't heard of this before. 
:fries:

**Review by anuragbhatnagar — APPROVED** [review]
LGTM!

**Comment by anuragbhatnagar** [comment]
I think the `#import <AirshipKit/AirshipKit.h>` statement in `SEGUrbanAirshipIntegration.m` file should be `#import "AirshipKit.h"`
Right now the project doesn't compile for me with this commit.
`/Code/Pods/Segment-UrbanAirship/Pod/Classes/SEGUrbanAirshipIntegration.m:28:9: 'AirshipKit/AirshipKit.h' file not found`

**Pull request merged**
